CREATE ROLE approle LOGIN PASSWORD 'sori883';

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public to approle;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public to approle;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public to approle;